#!/bin/sh

echo "Running post-installation script"
# Add your post-install commands here
echo "Verifying banner file ownership:"
ls -l /etc/banner
opkg search /etc/banner
/etc/init.d/tollgate-basic restart
exit 0